services:
  postgres:
    image: postgres:17
    container_name: ticket-reservation-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: event-reservation 
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
